#!/usr/bin/env bash
# Build, sign and publish a MkCleaner release.
#
# The updater fetches a signed manifest from the GitHub release; every build
# must be signed with the private key kept OUT of this repository, at
# ~/.mkcleaner/mkcleaner.key (generated by `pnpm tauri signer generate`).
#
# Usage:
#   ./scripts/release.sh <version>            # e.g. ./scripts/release.sh 0.2.0
#   GH_TOKEN=xxx ./scripts/release.sh 0.2.0   # also publish the release

set -euo pipefail

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
    echo "usage: $0 <version>" >&2
    exit 1
fi

KEY="$HOME/.mkcleaner/mkcleaner.key"
if [[ ! -f "$KEY" ]]; then
    echo "missing signing key at $KEY — run 'pnpm tauri signer generate -w $KEY'" >&2
    exit 1
fi

export TAURI_SIGNING_PRIVATE_KEY_PATH="$KEY"

echo "==> Bumping version to $VERSION"
# The three places the version lives.
node -e "
const fs = require('fs');
for (const file of ['package.json', 'src-tauri/tauri.conf.json', 'src-tauri/Cargo.toml']) {
    let text = fs.readFileSync(file, 'utf8');
    text = text.replace(/(\"version\"\s*:\s*\")[^\"]+/, \`\$1$VERSION\`);
    fs.writeFileSync(file, text);
}
"

echo "==> Building (universal)"
pnpm tauri build --bundles app,dmg

BUNDLE="src-tauri/target/release/bundle"
APP_ARCH="aarch64-apple-darwin"
TARGET="$APP_ARCH"

# The signed update artifacts the build produced.
SIG="$BUNDLE/macos/$TARGET/MkCleaner.app.tar.gz.sig"
MANIFEST="$(ls "$BUNDLE"/macos/$TARGET/latest-*.json 2>/dev/null | head -1 || true)"

if [[ -z "$MANIFEST" || ! -f "$SIG" ]]; then
    echo "!! updater artifacts not found — check tauri.conf.json plugins.updater" >&2
    exit 1
fi

echo "==> Release artifacts"
ls -lh "$BUNDLE/dmg/"*.dmg "$BUNDLE/macos/$TARGET/MkCleaner.app.tar.gz" "$SIG" "$MANIFEST"

if [[ -n "${GH_TOKEN:-}" ]]; then
    echo "==> Publishing GitHub release v$VERSION"
    gh release create "v$VERSION" \
        "$BUNDLE/dmg/"*.dmg \
        "$BUNDLE/macos/$TARGET/MkCleaner.app.tar.gz" \
        "$SIG" \
        "$MANIFEST" \
        --latest --title "MkCleaner $VERSION" --notes "See the changelog in the repository."
    echo "done — the app's next launch will offer the update."
else
    echo
    echo "Built and signed. Publish with:"
    echo "  gh release create v$VERSION \\"
    echo "      $BUNDLE/dmg/*.dmg \\"
    echo "      $BUNDLE/macos/$TARGET/MkCleaner.app.tar.gz \\"
    echo "      $SIG $MANIFEST --latest"
fi
