#!/usr/bin/env bash
# Build, sign and publish a MkCleaner release.
#
# The updater fetches a signed manifest from the GitHub release; every build
# must be signed with the private key kept OUT of this repository, at
# ~/.mkcleaner/mkcleaner.key (generated by `pnpm tauri signer generate`).
#
# Usage:
#   ./scripts/release.sh <version>            # e.g. ./scripts/release.sh 0.2.0
#   GH_TOKEN=xxx ./scripts/release.sh 0.2.0   # also publish the release

set -euo pipefail

# Non-login shells (CI, background tasks) may lack cargo on PATH.
if [[ -d "$HOME/.cargo/bin" && ":$PATH:" != *":$HOME/.cargo/bin:"* ]]; then
    export PATH="$HOME/.cargo/bin:$PATH"
fi

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
    echo "usage: $0 <version>" >&2
    exit 1
fi

KEY="$HOME/.mkcleaner/mkcleaner.key"
if [[ ! -f "$KEY" ]]; then
    echo "missing signing key at $KEY — run 'pnpm tauri signer generate -w $KEY'" >&2
    exit 1
fi

# The build's updater signing reads the key from the content variable;
# the file path alone is not enough in a non-interactive shell.
export TAURI_SIGNING_PRIVATE_KEY="$(cat "$KEY")"
export TAURI_SIGNING_PRIVATE_KEY_PATH="$KEY"
export TAURI_SIGNING_PRIVATE_KEY_PASSWORD=""

echo "==> Bumping version to $VERSION"
node -e "
const fs = require('fs');
for (const file of ['package.json', 'src-tauri/tauri.conf.json', 'src-tauri/Cargo.toml']) {
    let text = fs.readFileSync(file, 'utf8');
    text = text.replace(/(\"version\"\s*:\s*\")[^\"]+/, \`\$1$VERSION\`);
    fs.writeFileSync(file, text);
}
"

echo "==> Building (universal)"
pnpm tauri build --bundles app,dmg --target universal-apple-darwin

BUNDLE="src-tauri/target/universal-apple-darwin/release/bundle"
APP_ARCHIVE="$BUNDLE/macos/MkCleaner.app.tar.gz"
SIG="$APP_ARCHIVE.sig"

if [[ ! -f "$SIG" ]]; then
    echo "!! updater signature not found — check tauri.conf.json plugins.updater and the signing key" >&2
    exit 1
fi

# tauri-cli signs the archive but does not write the manifest; produce one per
# naming scheme. The updater plugin looks up `latest-{{target}}.json` where
# {{target}} is the runtime's own os(-arch) form (`darwin`, `darwin-aarch64`),
# while CI tooling conventionally names manifests after the Rust triple
# (`aarch64-apple-darwin`). All point at the same universal archive, so the
# signature is the same and only the file names differ.
RELEASE_URL="https://github.com/HanversionOvO/MKCleaner/releases/download/v$VERSION/MkCleaner.app.tar.gz"
SIGNATURE="$(cat "$SIG")"
PUB_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Every manifest lists every possible platform key: the updater plugin matches
# on `{os}-{arch}` and `{os}-{arch}-{installer}` fallbacks, CI tooling uses the
# Rust triple, and all point at the same universal archive.
PLATFORMS='darwin-aarch64-app darwin-aarch64 darwin-x86_64-app darwin-x86_64 darwin aarch64-apple-darwin x86_64-apple-darwin'

MANIFESTS=()
for TARGET in $PLATFORMS; do
    MANIFEST="$BUNDLE/macos/latest-$TARGET.json"
    node -e "
const fs = require('fs');
const platforms = {};
for (const t of '$PLATFORMS'.split(' ')) {
    platforms[t] = { signature: '$SIGNATURE', url: '$RELEASE_URL' };
}
fs.writeFileSync('$MANIFEST', JSON.stringify({
    version: '$VERSION',
    notes: '',
    pub_date: '$PUB_DATE',
    platforms,
}, null, 2) + '\n');
"
    MANIFESTS+=("$MANIFEST")
done

echo "==> Release artifacts"
ls -lh "$BUNDLE/dmg/"*.dmg "$APP_ARCHIVE" "$SIG" "${MANIFESTS[@]}"

if [[ -n "${GH_TOKEN:-}" ]]; then
    echo "==> Publishing GitHub release v$VERSION"
    gh release create "v$VERSION" \
        "$BUNDLE/dmg/"*.dmg \
        "$APP_ARCHIVE" \
        "$SIG" \
        "${MANIFESTS[@]}" \
        --latest --title "MkCleaner $VERSION" --notes "See the changelog in the repository."
    echo "done — the app's next launch will offer the update."
else
    echo
    echo "Built and signed. Publish with:"
    echo "  gh release create v$VERSION \\"
    echo "      $BUNDLE/dmg/*.dmg \\"
    echo "      $APP_ARCHIVE \\"
    echo "      $SIG \\"
    echo "      ${MANIFESTS[*]} --latest"
fi
